### ISSUE TITLE
Namespace does not load dictionary in list of entries (data.yaml)

### ISSUE THREAD

**Issue by Ahleroy** [Deeplodocus/deeplodocus#96]
With the following data.yaml file :

```yaml
enable :
  train: True
  validation: True
  test: True
dataloader:
  batch_size: 4
  num_workers: 4
dataset:
  train:
    number: 100
    load_method: "default" #default (from memory), hard drive, ...
    inputs:
      - path: ['./data/input1.txt']
        join: Null # Null, auto, "some/path"      # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
      - path: ['./data/input2.txt']
        join: Null                                # (Optional) Null, auto, "some/path"
        type: "image"                             # (Optional) image, video, integer, label,
```

The inputs are loaded into a list of strings instead of a list of dictionary by the Namespace.
